(define (problem hanoi5)
  (:domain hanoi)
  (:objects loc1 loc2 loc3 box1 box2 box3 fetch - object)
  (:init
   (bigger loc1 box1)
   (bigger loc1 box2)
   (bigger loc2 box1)
   (bigger loc2 box2)
   (bigger loc2 box3)
   (bigger loc3 box1)
   (bigger loc3 box2)
   (clear loc2)
   (clear loc3)
   (clear box1)
   (on box2 loc1)
   (on box1 box2)
   (robot fetch)
  )

  (:goal (and
    (on box1 loc3)
    )
  )
)
