(define (problem hanoi3)
  (:domain hanoi)
  (:objects loc1 loc2 loc3 box1 box2 box3 fetch - object)
  (:init
   (bigger loc1 box1)
   (bigger loc1 box2)
   (bigger loc1 box3)
   (bigger loc2 box1)
   (bigger loc2 box2)
   (bigger loc2 box3)
   (bigger loc3 box1)
   (bigger loc3 box2)
   (bigger loc3 box3)
   (clear loc2)
   (clear loc3)
   (clear box1)
   (on box3 loc1)
   (on box2 box3)
   (on box1 box2)
   (robot fetch)
   (bigger box3 box2)
   (bigger box2 box1)
  )

  (:goal (and
    (on box3 loc3)
    (on box2 box3)
    (on box1 box2)
    )
  )
)