(define (domain keva)
  (:requirements :strips :typing :conditional-effects)
  
  (:types robot plank orientated location)
  (:predicates
  		   (onTable ?p - plank)
  		   (inBuffer ?p - plank)
  		   (onSinglePlank ?p - plank ?p - plank)
           (onDoublePlank ?p - plank ?p - plank ?p - plank)
           (clearPlank ?p - plank)
  		   (handempty)
             (completed)
  		   (inGripper ?p - plank)
  		   (orientation ?o - orientated ?p - plank)
           (placed ?p - plank)
           (human_placed ?loc - location ?p - plank )
           (free ?loc - location))


  (:action pickUp_plank
  		 :parameters (?loc - location ?p - plank ?rob - robot)
  		 :precondition (and (handempty)
                            (clearPlank ?p)
                            (or (human_placed ?loc ?p )(inBuffer ?p)))
  		 :effect (and (not (handempty))
                      (inGripper ?p)
                      (not (clearPlank ?p))
                      (not (onTable ?p))
                      (when (human_placed ?loc ?p ) (not (human_placed ?loc ?p)))
                      (when (not (free ?loc))(and (free ?loc)))
                      (when (inBuffer ?p)(and (not (inBuffer ?p))))
                      ;(forall (?pl - plank)
                    ;     (when (and (onSinglePlank ?p ?pl)
                     ;                  (not (= ?p ?pl)))
                      ;            (and (not(onSinglePlank ?p ?pl))
                       ;                (clearPlank ?pl))))
                                       )
  )



  (:action putDown_plank_onTable
  		 :parameters (?o - orientated ?p - plank ?rob - robot)
  		 :precondition (and (not (handempty))
                            (inGripper ?p)
                            (not (placed ?p))
                            (or (= ?o vertical) (= ?o sideways))
                        )
  		 :effect (and (handempty)
                      (onTable ?p)
                      (clearPlank ?p)
                      (orientation ?o ?p)
                      (not (inGripper ?p))
                      (placed ?p))
  )

  (:action putDown_plank_onPlank
  		 :parameters (?o - orientated ?p1 - plank ?p2 - plank ?rob - robot)
  		 :precondition (and (not (handempty))
                          (inGripper ?p1)
                          (not (= ?p1 ?p2))
                          (not (placed ?p1))
                          (placed ?p2))
  		 :effect (and (handempty)
                      (onSinglePlank ?p1 ?p2)
                      (not (clearPlank ?p2))
                      (orientation ?o ?p1)
                      (not (inGripper ?p1))
                      (clearPlank ?p1)
                      (placed ?p1))
  )

  (:action putDown_plank_onDoublePlank
  		 :parameters (?o - orientated ?p1 - plank ?p2 - plank ?p3 - plank ?rob - robot)
  		 :precondition (and (not (handempty))
                            (inGripper ?p1)
                            (not (= ?p1 ?p2))
                            (not (= ?p1 ?p3))
                            (not (= ?p2 ?p3))
                            (not (= ?o vertical))
                            (not (placed ?p1))
                            (placed ?p2)
                            (placed ?p3)
                            (or
                                (and (orientation horizontal ?p2)
                                     (orientation horizontal ?p3))
                                (and (orientation vertical   ?p2)
                                     (orientation vertical   ?p3))
                                (and (orientation sideways   ?p2)
                                     (orientation sideways   ?p3))))
  		 :effect (and (handempty)
                      (not (inGripper ?p1))
                      (onDoublePlank ?p1 ?p2 ?p3)
                      (orientation ?o ?p1)
                      (not (clearPlank ?p2))
                      (not (clearPlank ?p3))
                      (clearPlank ?p1)
                      (placed ?p1))
  )



  (:action human_place
    :parameters (?l - location ?p - plank )
    :precondition (and (handempty)
          (free ?l)
    )
    :effect (and
        (human_placed ?l ?p)
        (not (free ?l))
        (clearPlank ?p)
    )
  )

)