# Generated by Django 3.2.5 on 2021-08-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0002_auto_20210312_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebooksmodel',
            old_name='docs',
            new_name='domain',
        ),
    ]
