# Generated by Django 3.2.5 on 2021-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0003_rename_docs_ebooksmodel_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='domain',
            field=models.FilePathField(allow_folders=True, null=True, path='/home/kyle/JEDAI/test_domains'),
        ),
    ]
