# Generated by Django 3.2.5 on 2021-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0011_auto_20210812_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='domain',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/home/kyle/JEDAI/modules'),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='problem',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/home/kyle/JEDAI/modules'),
        ),
    ]
