# Generated by Django 3.2.5 on 2021-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0012_auto_20210812_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='problem',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/home/kyle/JEDAI/modules', recursive=True),
        ),
    ]
