# Generated by Django 3.2.5 on 2021-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0013_alter_ebooksmodel_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='problem',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, match='problem', null=True, path='/home/kyle/JEDAI/modules', recursive=True),
        ),
    ]
