# Generated by Django 3.2.5 on 2021-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0014_alter_ebooksmodel_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTheFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.FileField(upload_to='documents/')),
                ('problem', models.FileField(upload_to='documents/')),
                ('env', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
