# Generated by Django 3.2.5 on 2021-08-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roblocks', '0015_savethefiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveTheFiles',
        ),
    ]
